[tool.poetry]
name = "tbx"
version = "0.1.0"
description = "Torchbox.com"
authors = ["Torchbox Ltd"]

[tool.poetry.dependencies]
python = "^3.6"
django = "~2.2"
wagtail = "~2.10"
psycopg2 = "~2.8"
gunicorn = {version = "~20.0", optional = true}
wagtail-django-recaptcha = "1.0"
django-pattern-library = "~0.2"
whitenoise = "~5.0"
dj-database-url = "~0.5"
raven = "~6.10"
django-redis = "~4.11"
django-storages = { version ="~1.9", extras = ["boto3"] }
django-referrer-policy = "~1.0"
django-csp = "~3.6"
scout-apm = "~2.10"
django-basic-auth-ip-whitelist = "~0.3.3"
wagtail-accessibility = "~0.2"
wagtail-storages = "~0.0.4"
wagtail-markdown = "^0.6"
wagtailfontawesome = "^1.2.1"
django-phonenumber-field = "^5.0.0"
phonenumbers = "^8.12.12"

[tool.poetry.extras]
gunicorn = ["gunicorn"]

[tool.poetry.dev-dependencies]
Werkzeug = "~0.16"
django-extensions = "~2.2"
fabric = "~2.5"
stellar = "~0.4"

# Linters etc.
black = "19.10b0"
detect-secrets = "~0.13"
flake8 = "3.7.7"
isort = "4.3.21"
pre-commit = "~2.0"
seed-isort-config = "1.9.4"

# Documentation
mkdocs = "~1.0"

[build-system]
requires = ["poetry>=1,<2"]
build-backend = "poetry.masonry.api"
