context:
  page:
    title: Service
    get_verbose_name: service
    hero:
      title: The digital product agency <span>for tomorrow’s nonprofits</span>.
      in_page_nav:
        - { title: Services, href: services }
        - { title: Clients, href: clients }
        - { title: Thinking, href: thinking }
    clients:
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
    quotes:
      - {
          quote: Thank you for your amazing and continued partnership Torchbox - our new website exceeds expectations!,
          name: Sarah Toms,
          role: Executive Director,
          Wharton Interactive at The Wharton School,
        }
      - {
          quote: Thank you for your amazing and continued partnership Torchbox - our new website exceeds expectations!,
          name: Sarah Toms,
          role: Executive Director,
          Wharton Interactive at The Wharton School,
        }
      - {
          quote: Thank you for your amazing and continued partnership Torchbox - our new website exceeds expectations!,
          name: Sarah Toms,
          role: Executive Director,
          Wharton Interactive at The Wharton School,
        }
    casestudies:
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
    blogs:
      - {
          title: We already dropped Drupal - maybe it’s time for you to do the same.,
          date: 20 Oct '20,
          author_name: Paul Vetch,
          author_role: Strategy Director,
        }
      - {
          title: Wagtail for Public Sector,
          date: 20 Oct '20,
          author_name: Will Heinemann,
          author_role: New Business Director,
        }
      - {
          title: We already dropped Drupal - maybe it’s time for you to do the same.,
          date: 20 Oct '20,
          author_name: Paul Vetch,
          author_role: Strategy Director,
        }
      - {
          title: Wagtail for Public Sector,
          date: 20 Oct '20,
          author_name: Will Heinemann,
          author_role: New Business Director,
        }
      - {
          title: We already dropped Drupal - maybe it’s time for you to do the same.,
          date: 20 Oct '20,
          author_name: Paul Vetch,
          author_role: Strategy Director,
        }
  see_more_casestudies:
    text: See more casestudies
    href: '/work'
  see_more_blogs:
    text: See more blogs
    href: '/blogs'
