name: check_copy_prod_to_staging_status
# The following secrets are required on GitHub:
#   - FLIGHTPATH_URL (URL for the flightpath excluding trailing slash)
#   - FLIGHTPATH_AUTH_KEY (from flightpath)
run-name: Check status of production to staging by @${{ github.actor }}
on: [workflow_dispatch]
inputs:
  job_id:
    description: 'Flightpath job id'
    required: true
    type: string
concurrency: staging_environment
jobs:
  run_flightpath_status_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Run run_flightpath_status_check.py script
        run: |
          python tbx/core/utils/scripts/run_flightpath_status_check.py --job_id=${{ inputs.job_id }}
        env:
          FLIGHTPATH_AUTH_KEY: ${{ secrets.FLIGHTPATH_AUTH_KEY }}
          FLIGHTPATH_URL: ${{ secrets.FLIGHTPATH_URL }}
